# Generated by Django 2.2.7 on 2019-11-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, verbose_name='ユーザー名')),
                ('password1', models.CharField(default='password1', max_length=12, verbose_name='パスワード１')),
                ('password2', models.CharField(default='password2', max_length=12, verbose_name='パスワード２')),
            ],
        ),
    ]
