# Generated by Django 2.2.7 on 2019-11-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='映画タイトル')),
                ('release_date', models.CharField(default='----年--月--日', max_length=11, verbose_name='公開日')),
                ('income', models.IntegerField(default=0, verbose_name='興行収入')),
            ],
        ),
    ]
