# Generated by Django 2.2.7 on 2019-11-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191126_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='income_str',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
