# Generated by Django 2.2.7 on 2019-11-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_movie_income_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='income',
            field=models.FloatField(default=0, verbose_name='興行収入'),
        ),
    ]
